[package]
name = "acolpi"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
secrecy = { version = "0.10.3", features = ["serde"] }
thiserror = "2.0.21"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
amplify = { version = "4.9", default-features = false, features = ["derive"] }
